import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "DEXLUNA | Softweare Solutions",
  description:
    "Software Solutions for your business, powered by Next.js 14 and React.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "software development",
    "custom software solutions",
    "web app development",
    "mobile app development",
    "next.js developers",
    "react developers",
    "freelance developer",
    "fullstack developer",
    "frontend developer",
    "backend developer",
    "javascript developer",
    "typescript expert",
    "api integration",
    "UI/UX design",
    "cloud software",
    "SaaS development",
    "node.js development",
    "enterprise software",
    "agile software company",
    "software company portfolio",
    "Softwareentwicklung",
    "Webanwendung entwickeln",
    "Individuelle Softwarelösungen",
    "Mobile App Entwicklung",
    "Fullstack Entwickler",
    "React Entwickler",
    "Next.js Agentur",
    "JavaScript Entwickler",
    "TypeScript Entwickler",
    "UI/UX Design Agentur",
    "Softwareagentur Deutschland",
    "API Integration",
    "Cloud Softwarelösungen",
    "Maßgeschneiderte Software",
    "SaaS Entwicklung",
    "Backend Entwicklung",
    "Frontend Entwicklung",
    "zhvillim softueri",
    "kompani softuerike",
    "zhvillim aplikacionesh web",
    "zhvillim aplikacionesh mobile",
    "zhvillues fullstack",
    "zhvillues frontend",
    "zhvillues backend",
    "softuer me porosi",
    "zhvillim react",
    "zhvillim nextjs",
    "ekspert javascript",
    "ekspert typescript",
    "UI/UX dizajn",
    "integrim API",
    "zhvillim softuerësh cloud",
    "faqe interneti profesionale",
    "agjenci dizajni dhe zhvillimi",
  ] as Array<string>,
  authors: {
    name: "FestimBEQIRI",
    url: "https://github.com/festimii",
  },
} as const;
